# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170808_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='photo_card',
        ),
    ]
